import React from "react";
import Head from "next/Head";
import Script from "next/script";
var FormData = require("form-data");
import { useEffect, useState } from "react";
import Router from "next/router";
import { getCookie } from "cookies-next";
import Profile from "./Profile";
var FormData = require('form-data');

const Modal = () => {
//   const [info, setinfo] = useState({ name: "" , city: "" , user_type: ""})
//  const usertoken = getCookie("user")

//   const profilesetup = (name , city , user_type) => {
//     var myHeaders = new Headers();
//     myHeaders.append("Accept", "application/json");
//     myHeaders.append(
//       "Authorization",
//           "Bearer "+ usertoken
//     );

//     var formdata = new FormData();
//     formdata.append(name, "");
//     formdata.append(city, "");
//     formdata.append(user_type, "");

//     var requestOptions = {
//       method: "POST",
//       headers: myHeaders,
//       body: formdata,
//       redirect: "follow",
//     };

//     fetch(
//       "https://truck.pantheondigitals.com/api/profile-setup",
//       requestOptions
//     )
//       .then((response) => response.json())
//       .then((result) => {for (let index = 0; index < result.length; index++) {
//           result[index].name = name;
//           result[index].city = city;
//           result[index].user_type = user_type;
        
//       }})
//       .catch((error) => console.log("error", error));
//   };
  
//   const updateNote = (Currentnote) => {
//     ref.current.click();
//     setinfo({name:Currentnote.name,city:Currentnote.city,user_type:Currentnote.user_type});
//  };
//   const onChange = (e)=>{
//     setinfo({...info, [e.target.name]: e.target.value})
// }
// const handleClick = (e)=>{
//   e.preventDefault();
//   profilesetup(info.name,info.city,info.user_type);
// }
  return (
    <>
      <Head>
        <title>Your Dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossOrigin="anonymous"
        />
      </Head>
      <button data-bs-toggle="modal" data-bs-target="#exampleModal" id="btncss">
        Open
      </button>
      <div
        className="modal fade"
        id="exampleModal"
        tabIndex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title" id="exampleModalLabel">
                User Information
              </h5>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div className="modal-body">
              <div className="d-flex flex-column justify-content-center">
                <div className="mb-3">
                  <label htmlFor="exampleInputEmail1" className="form-label">
                    Name
                  </label>
                  <input
                  
                  
                    name="name"
                    type="text"
                    className="form-control inputwidth"
                    id="name"
                    aria-describedby="name"
                  />
                </div>

                <div className="form-group">
                  <label htmlFor="city" className="form-label">
                    Enter Your City
                  </label>
                  <input
                    
                   
                    type="text"
                    name="city"
                    className="form-control inputwidth"
                    list="from"
                  />
                </div>
                <div className="form-group my-3">
                  <label htmlFor="email" className="form-label">
                    Select Category
                  </label>
                  <input
                    
                   
                    type="text"
                    name="city"
                    className="form-control inputwidth"
                  />
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button
                type="button"
                className="btn btn-secondary"
                data-bs-dismiss="modal"
              >
                Close
              </button>
              <button type="button" className="btn btn-primary" >
                Save changes
              </button>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossOrigin="anonymous"
      />
      <Profile/>
    </>
  );
};

export default Modal;
