import React from 'react'
import Head from "next/Head";
import Script from "next/script";

const Modal = () => {
    const name = () => {
        // const name = document.getElementById("name").value;
        // console.log(name);
        console.log("sagar");
      };
  return (
    <>
     <Head>
        <title>Your Dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />
      </Head>
    <button data-bs-toggle="modal"
                data-bs-target="#exampleModal">Open</button>
    <div
    className="modal fade"
    id="exampleModal"
    tabIndex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div className="modal-dialog">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title" id="exampleModalLabel">
            Modal title
          </h5>
          <button
            type="button"
            className="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div className="modal-body">
          <div className="d-flex flex-column justify-content-center">
            <div className="mb-3">
              <label htmlFor="exampleInputEmail1" className="form-label">
                Name
              </label>
              <input
                type="text"
                className="form-control inputwidth"
                id="name"
                aria-describedby="name"
              />
            </div>
            <div className="mb-3">
              <label htmlFor="email" className="form-label">
                Email
              </label>
              <input
                type="email"
                className="form-control inputwidth"
                id="email"
              />
            </div>
            <div className="form-group">
              <label htmlFor="city" className="form-label">
                Enter Your City
              </label>
              <input
                type="text"
                name="s"
                className="form-control inputwidth"
                list="from"
              />
              <datalist id="from">
                <option>Gurgaon</option>
              </datalist>
            </div>
            <div className="form-group my-3">
              <label htmlFor="email" className="form-label">
                Select Category
              </label>
              <select
                name="type"
                className="btn-primary form-control inputwidth"
              >
                <option value="Load">Truck Owner</option>
                <option value="Lorry">Loads Owner</option>
              </select>
            </div>
          </div>
        </div>
        <div className="modal-footer">
          <button
            type="button"
            className="btn btn-secondary"
            data-bs-dismiss="modal"
            onClick={name}
          >
            Close
          </button>
          <button type="button" className="btn btn-primary" onClick={name}>
            Save changes
          </button>
        </div>
      </div>
    </div>
  </div>
  <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossOrigin="anonymous"/>
  </>
  )
}

export default Modal