import React from 'react'
import Head from "next/Head";
import Script from "next/script";


export const Navbarp = ({ opennav ,closeNav}) => {
  return (
    <>
      <Head>
        <title>Your Dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />
      </Head>
      <div id="burger" onClick={opennav}>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
        <div id="cross" onClick={closeNav}>
        <i class="fa-solid fa-2x fa-circle-xmark"></i>

        </div>

      <div className='d-flex flex-column my-5'>

        <div class="d-flex" style={{ "overflow": "hidden" }}>
          <div className=' my-4 mx-3 font-awed'>
            <i class="fa-solid fa-2x fa-house-user font-awe"></i>
          </div>
          <div class="my-4 py-1 mx-5 colrs">
            Home
          </div>
        </div>
        <div class="d-flex" style={{ "overflow": "hidden" }}>
          <div className=' my-4 mx-3 font-awed'>
            <i class="fa-solid fa-2x fa-house-user font-awe"></i>
          </div>
          <div class="my-4 py-1 mx-5 colrs">
            Home
          </div>
        </div>
        <div class="d-flex" style={{ "overflow": "hidden" }}>
          <div className=' my-4 mx-3 font-awed'>
            <i class="fa-solid fa-2x fa-house-user font-awe"></i>
          </div>
          <div class="my-4 py-1 mx-5 colrs">
            Home
          </div>
        </div>
        <div class="d-flex" style={{ "overflow": "hidden" }}>
          <div className=' my-4 mx-3 font-awed'>
            <i class="fa-solid fa-2x fa-house-user font-awe"></i>
          </div>
          <div class="my-4 py-1 mx-5 colrs">
            Home
          </div>
        </div>


      </div>


      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossOrigin="anonymous" />
      <Script src="https://kit.fontawesome.com/c378079259.js" crossOrigin="anonymous" />
    </>
  )
}
export default Navbarp