import React from 'react';
import Router from "next/router";
import {useRouter} from "next/router";
import Navbarp from './Navbarp';
import Head from "next/Head";
import Script from "next/script";
import { getCookie } from 'cookies-next';

const Profile = (props) => {
    const router = useRouter();
    if(getCookie("user") === undefined){
    router.push("../Login")
    }
    const openNav = () => {
        // if( document.getElementById('sidenav').style.width == "6%"){
        document.getElementById('sidenav').style.width = "20%";
        document.getElementById('mainbox').style.width = "80%";
        document.getElementById('burger').style.display = "none";
        document.getElementById('cross').style.display = "block";
        document.getElementById('cross').style.transitionDelay = "2s";
        // }
    }
    const closeNav = () => {
        document.getElementById('sidenav').style.width = "6%";
        document.getElementById('mainbox').style.width = "94%";
        document.getElementById('burger').style.transition = "1s";
        document.getElementById('burger').style.display = "block";
        document.getElementById('cross').style.display = "none";
    }
    return (
        <>

            <Head>
                <title>Your Dasboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
                    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
                    crossOrigin="anonymous" />
            </Head>
            <div id="maincontainer">
                <div id='sidenav' className='' style={{ "height": "100vh", "backgroundColor": "rgb(255,138,41)" }}>

                    <Navbarp opennav={openNav} closeNav={closeNav} />

                </div>
                <div id="mainbox">
                    <div className='my-2'>
                        <h2 class="h-center">Profile</h2>
                    </div>
                    {/* <div className='text-center'>
                        <Image src="/profile.jpg" height={100} width={100} className="imgp" />
                        <i class="fa-solid fa-pen-to-square fonti"></i>
                    </div> */}


                </div>
            </div>
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossOrigin="anonymous" />
            <Script src="https://kit.fontawesome.com/c378079259.js" crossOrigin="anonymous" />
        </>
    )
}

export default Profile
