import Head from 'next/Head'
import React from 'react'
import Navbar from './components/Navbar'
import Script from "next/script";

export const Login = () => {
  return (
   <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossOrigin="anonymous"
        />
      </Head>
      <Navbar/>
     <div className="row">
        <div className="col-md-6 mt-5">
            <div className="my-5 mx-5 photod">
               
            </div>
        </div>
        <div className="col-md-6">
            <div className="my-5 mx-5 divs">
                <h1 className="text-center">
                    WElCOME TO TRUCK
                </h1>
              <h5 className="text-muted text-center my-3">Enter mobile number to continue and signup to truck</h5>
              <div class="d-flex justify-content-center">
                <input type="text" className='inpn my-5' list='country'/>
                <datalist id='country'>
                  <option>+91</option>

                </datalist>
                <div  className='my-5 px-2'>
                <input type="number" className=" inps" id="number" aria-describedby="numberhelp"/>
                </div>

              </div>
              <div className="text-center">
              <button className="btn btn-cus my-5 my-sm-0 px-4 py-2 btnlogin"> <a
                    type="button" style={{  "textdecoration": "none" }}
                    href="Otp">Send OTP</a></button>
                    </div>
                <div className='text-center my-3'>
                    <p>
                        By providing my phone number,I hereby agree the <a style={{"color": " #f36546"}}>terms of services</a>
                    </p>
                </div>
            </div>
        </div>
     </div>
     <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossOrigin="anonymous"
      />
   </>
  )
}
export default Login