import Head from 'next/Head'
import React from 'react'
import Navbar from './components/Navbar'
import Script from "next/script";
import Profile from './User/Profile';

export const Otp = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
                    crossOrigin="anonymous"
                />
            </Head>
            <Navbar />
            <div className="row">
                <div className="col-md-6 mt-5">
                    <div className="my-5 mx-5 photod">

                    </div>
                </div>
                <div className="col-md-6">
                    <div className="my-5 mx-5 divs">
                        <h1 className="text-center">
                            Verify the OTP
                        </h1>
                        <h5 className="text-muted text-center my-3">Enter the OTP you have recieved on your phone number</h5>
                        <div className='my-5 d-flex justify-content-center'>
                            <input
                                type="number"
                                inputMode="numeric"
                                pattern="\d"
                                title="Numeric"
                                id="code1"
                                name="tfaValue"
                                className="text-center inpsotp w-8 xxs:w-12 mx-1"
                                maxLength="1"                              
                                required
                            />

                            <input
                                type="number"
                                inputMode="numeric"
                                pattern="\d"
                                title="Numeric"
                                id="code2"
                                name="tfaValue"
                                className="text-center inpsotp w-8 xxs:w-12 mx-1"
                                maxLength="1"
                                required
                            />

                            <input
                                type="number"
                                inputMode="numeric"
                                pattern="\d"
                                title="Numeric"
                                id="code3"
                                name="tfaValue"
                                className="text-center w-8 inpsotp xxs:w-12 mx-1"
                                maxLength="1"
                                required
                            />

                            <input
                                type="number"
                                inputMode="numeric"
                                pattern="\d"
                                title="Numeric"
                                id="code4"
                                name="tfaValue"
                                className="text-center w-8 inpsotp xxs:w-12 mx-1"
                                maxLength="1"
                                required
                            />
                        </div>
                        <div className='text-center my-3'>
                            <p>
                                Didn't recieve Otp code <a style={{ "color": " #f36546" }}>Resend Code</a>
                            </p>
                        </div>
                        <div className="text-center">
                            <button className="btn btn-cus my-5 my-sm-0 px-4 py-2 bt btnlogin"> <a
                                type="button" style={{ "textdecoration": "none" }}
                                href='./User/Profile'>Verify</a></button>
                        </div>
                    </div>
                </div>
            </div>
            <Script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
                crossOrigin="anonymous"
            />
        </>
    )
}
export default Otp